version: '3'
services:

  redis:
    image: redis
    networks:
      main:
        aliases:
          - redis

  mongoDB:
    image: mongo:latest
    networks:
      main:
        aliases:
          - mongo

  apigateway:
    depends_on:
      - redis
      - mongoDB
    build:
      context: git://github.com/bongi23/PLANTS-server.git
      dockerfile: Dockerfile-server
    ports:
      - "8080:8080"
    environment:
      - "REDIS=redis://redis"
      - "MONGODB=mongodb://mongo:27017/plantsDB"
    networks:
      main:

  celery:
    depends_on:
      - redis
      - mongoDB
      - apigateway
    build:
      context: git://github.com/bongi23/PLANTS-server.git
      dockerfile: Dockerfile-celery
    environment:
      - "REDIS=redis://redis"
      - "MONGODB=mongodb://mongo27017/plantsDB"
    networks:
      main:


networks:
  main:
