FROM python:3.7.3-alphine3.8

ADD requirements.txt ./app/
WORKDIR /app

RUN pip install -r requirements.txt

ADD . /app

CMD ["celery", "-A", "swagger_server.controllers.sink_controller.celery", "worker"]