version: '3'
services:

  redis:
    image: redis
    networks:
      main:
        aliases:
          - redis

  mongoDB:
    image: mongo:latest
    networks:
      main:
        aliases:
          - mongo

  apigateway:
    depends_on:
      - redis
    build:
      context: git://github.com/bongi23/PLANTS-server.git
    ports:
      - "8080:8080"
    environment:
      - "REDIS=redis://redis"
      - "MONGODB=mongodb://mongo"
    networks:
      main:

networks:
  main:
