# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Data(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, sensor: str=None, value: int=None, timestamp: int=None):  # noqa: E501
        """Data - a model defined in Swagger

        :param sensor: The sensor of this Data.  # noqa: E501
        :type sensor: str
        :param value: The value of this Data.  # noqa: E501
        :type value: int
        :param timestamp: The timestamp of this Data.  # noqa: E501
        :type timestamp: int
        """
        self.swagger_types = {
            'sensor': str,
            'value': int,
            'timestamp': int
        }

        self.attribute_map = {
            'sensor': 'sensor',
            'value': 'value',
            'timestamp': 'timestamp'
        }

        self._sensor = sensor
        self._value = value
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'Data':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The data of this Data.  # noqa: E501
        :rtype: Data
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sensor(self) -> str:
        """Gets the sensor of this Data.


        :return: The sensor of this Data.
        :rtype: str
        """
        return self._sensor

    @sensor.setter
    def sensor(self, sensor: str):
        """Sets the sensor of this Data.


        :param sensor: The sensor of this Data.
        :type sensor: str
        """
        if sensor is None:
            raise ValueError("Invalid value for `sensor`, must not be `None`")  # noqa: E501

        self._sensor = sensor

    @property
    def value(self) -> int:
        """Gets the value of this Data.


        :return: The value of this Data.
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value: int):
        """Sets the value of this Data.


        :param value: The value of this Data.
        :type value: int
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def timestamp(self) -> int:
        """Gets the timestamp of this Data.


        :return: The timestamp of this Data.
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: int):
        """Sets the timestamp of this Data.


        :param timestamp: The timestamp of this Data.
        :type timestamp: int
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501

        self._timestamp = timestamp
