# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EventParameter(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, sensor: str=None, threshold: List[int]=None, frequency: int=None):  # noqa: E501
        """EventParameter - a model defined in Swagger

        :param sensor: The sensor of this EventParameter.  # noqa: E501
        :type sensor: str
        :param threshold: The threshold of this EventParameter.  # noqa: E501
        :type threshold: List[int]
        :param frequency: The frequency of this EventParameter.  # noqa: E501
        :type frequency: int
        """
        self.swagger_types = {
            'sensor': str,
            'threshold': List[int],
            'frequency': int
        }

        self.attribute_map = {
            'sensor': 'sensor',
            'threshold': 'threshold',
            'frequency': 'frequency'
        }

        self._sensor = sensor
        self._threshold = threshold
        self._frequency = frequency

    @classmethod
    def from_dict(cls, dikt) -> 'EventParameter':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The event parameter of this EventParameter.  # noqa: E501
        :rtype: EventParameter
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sensor(self) -> str:
        """Gets the sensor of this EventParameter.


        :return: The sensor of this EventParameter.
        :rtype: str
        """
        return self._sensor

    @sensor.setter
    def sensor(self, sensor: str):
        """Sets the sensor of this EventParameter.


        :param sensor: The sensor of this EventParameter.
        :type sensor: str
        """

        self._sensor = sensor

    @property
    def threshold(self) -> List[int]:
        """Gets the threshold of this EventParameter.


        :return: The threshold of this EventParameter.
        :rtype: List[int]
        """
        return self._threshold

    @threshold.setter
    def threshold(self, threshold: List[int]):
        """Sets the threshold of this EventParameter.


        :param threshold: The threshold of this EventParameter.
        :type threshold: List[int]
        """

        self._threshold = threshold

    @property
    def frequency(self) -> int:
        """Gets the frequency of this EventParameter.


        :return: The frequency of this EventParameter.
        :rtype: int
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency: int):
        """Sets the frequency of this EventParameter.


        :param frequency: The frequency of this EventParameter.
        :type frequency: int
        """

        self._frequency = frequency
