# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, event_id: str=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param event_id: The event_id of this InlineResponse200.  # noqa: E501
        :type event_id: str
        """
        self.swagger_types = {
            'event_id': str
        }

        self.attribute_map = {
            'event_id': 'event_id'
        }

        self._event_id = event_id

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def event_id(self) -> str:
        """Gets the event_id of this InlineResponse200.


        :return: The event_id of this InlineResponse200.
        :rtype: str
        """
        return self._event_id

    @event_id.setter
    def event_id(self, event_id: str):
        """Sets the event_id of this InlineResponse200.


        :param event_id: The event_id of this InlineResponse200.
        :type event_id: str
        """

        self._event_id = event_id
