---
swagger: "2.0"
info:
  description: "Provides functions to P.L.A.N.T.S. sinks"
  version: "1.0.0"
  title: "P.L.A.N.T.S. sink api"
  license:
    name: "AGPL-v3.0"
    url: "https://www.gnu.org/licenses/agpl-3.0.en.html"
host: "localhost:8080"
tags:
- name: "plants"
  description: "Operations about plants"
schemes:
- "https"
- "http"
paths:
  /sink:
    put:
      tags:
      - "plants"
      summary: "Create a new plant"
      description: "This can be done by the sink"
      operationId: "add_plant"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "plant"
        description: "a plant object"
        required: true
        schema:
          $ref: "#/definitions/plant"
      responses:
        200:
          description: "Ok"
        400:
          description: "Missing infomation"
        409:
          description: "The plant already exists"
      x-swagger-router-controller: "swagger_server.controllers.plants_controller"
  /sink/{plant_id}:
    post:
      tags:
      - "plants"
      summary: "Set the sensed values"
      description: "Set sensed value for the microbit with plant_id."
      operationId: "set_values"
      consumes:
      - "application/json"
      parameters:
      - name: "plant_id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "data"
        required: false
        schema:
          type: "array"
          items:
            $ref: "#/definitions/data"
      responses:
        200:
          description: "Ok"
        400:
          description: "Bad request"
        404:
          description: "The plant doesn't exists"
      x-swagger-router-controller: "swagger_server.controllers.plants_controller"
definitions:
  data:
    properties:
      sensor:
        type: "string"
      value:
        type: "integer"
        format: "int64"
  plant:
    type: "object"
    properties:
      microbit:
        type: "integer"
        format: "int64"
      network:
        type: "integer"
        format: "int64"
      description:
        type: "string"
